### ISSUE TITLE
(Add option to) Re-use images from a previous build run

### ISSUE THREAD

**Issue by cyroxx** [exasol/script-languages-release#245]
WIth each build run, even if I make only a tiny change (one new apt or pip package in the customization part), it seems that the whole pipeline is run once again and results in a bunch of new docker images which consumes another couple of gigabytes.

This leads to the situation that on a small VM, with 20 GB, you can do 2-3 build runs maximum before you have to clean up the docker images and also the build cache (`.build/cache`, I believe) manually before another build run can be started.

Is there a strategy that has a smaller disk space footprint, e.g. by re-using docker layers/images from previous runs of that same flavor?

**Comment by tkilias** [comment]
Hi @cyroxx,

yes, I am aware of this short cumming. At the moment, I didn't have a good idea for that problem. What are your changes, because, usually, it should only rebuild build steps which changed?

If, I think so, about the problem, maybe, I can store the image names of the previous builds for a flavor and can check during the build, it these are still available and could use them for the cache.

Regarding using normal docker build cache, this is not really feasible to use it, because exaslct constructs the build context in a temporary directory and the name of this is each time different. So, docker doesn't recognize that it basically builds the same image with a slightly different build context. I will, think about if we can somehow reuse the temporary directory.

However, you could be right that we currently don't remove the build cache. This at least can be fixed fast. The other ideas, require quite substantial changes and first need to think about what really can work and how implement it.

**Comment by redcatbear** [comment]
@tkilias, please spawn tickets for the refactorings that are realistically doable (like cleaning the build cache) link to this ticket and close this ticket afterwards.

**Comment by cyroxx** [comment]
@tkilias We're using `exaslct clean-all-images` now (didn't know about the `clean-*` commands at the time of writing the OP), which keeps the disk space requirement to a minimum. Works for us, since we are only building one flavor anyway and do this rather seldomly.

**Comment by tkilias** [comment]
Hi @cyroxx, 

I created three issues for investigating some improvements regarding reusing images or caches. If you are interested in these, you can follow these tickets. I am going to close this issue, because the current issue is solved and the improvements deal with the long-term aspects of it.

If you have more questions or any other issue, let us know.
