### ISSUE TITLE
Create develop branch

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#294]
1. create GH Actions for checking that pull requests go to develop branch, and not to main. (does not prevent from merging, see protected branches settings)
2. create GH Actions to merge main branch back to develop branch after merge to main (necessary because there is still the option to merge directly from feature branches to main and because merging to main creates a new merge commit)

Overview:
1. We have a feature branch
2. Once feature branch is ready, we integrate the feature branch into the new develop branch via "Squash&Merge"
3. The develop branch might container several commits before we merge all changes to main branch, GCloud build will treat develop branch same way as "rebuild" branches.
4. Merge from develop branch to main happens via PullRequest: "Merge".
5. After integration to main, the GH Action (see above) merges main back to develop branch, via "Merge". (Good error handling!!!)

**Comment by tkilias** [comment]
- Merge from master to develop shouldn't be necessary for merges from develop to master -> less cluttered history
- CI breaker which checks if the pr goes to the correct branch, can check for the following branches or prefix 
  - feature/,... -> develop
  - hotfix,fast-path -> master (automatically applies rebuild)
  - develop (applies rebuild) -> master
- Use cherry pick instead of merge for master -> develop? Less cluttered history. We would have than two parallel linear histories
- Merge or cherry-pick from master to develop can have merge conflicts which prevent automatic merge. Nevertheless, we should try it first automatically.
- Submodules almost always produce merge conflicts. Nevertheless, we should try it first and potentially automatically try to use the submodule commit id which is newer.
- Or force automatically merge or cherry-pick and push a broken version to develop which needs to be fixed in develop (https://stackoverflow.com/questions/21051850/force-git-to-accept-cherry-picks-changes/32468531)
- I don't think we need the develop branch for the submodule, because we don't create releases from its master, it already works as develop branch.

**Comment by tkilias** [comment]
Here a visualization how the branch interactions and history should look like.

[script-languages-release-branch-model.pdf](https://github.com/exasol/script-languages-release/files/6838453/script-languages-release-branch-model.pdf)
[script-languages-release-branch-model.drawio.txt](https://github.com/exasol/script-languages-release/files/6838459/script-languages-release-branch-model.drawio.txt)

**Comment by tomuben** [comment]
Regarding the problem of the conflicts when merging from master => develop. We also could reset the develop branch to the same revision as the master was before the integration, and then just do a rebase/cherry-pick.

**Comment by tomuben** [comment]
I agree that we should not use a develop branch script-languages.
Now, if we don't use the develop branch for the submodule, we also won't have the problem with the submodule git sha in the submodule file, won't we?
Then we could use a simple squash cherry-pick from develop branch to master (and not a merge), which would simplify the git history, correct?

**Comment by tkilias** [comment]
We can have still collisions in the commit id for the submodule and these can't be solved automatically usually, except maybe with the --strategy theirs. 
The decision about merge and cherry-pick has nothing to do with submodule. It is only a decision, how we want to have the commit history to look like.
A cherry-pick will fail the same way as a merge in our cases, so there is not really a difference in using either of both. Except the look of the commit history.

**Comment by tomuben** [comment]
After some discussion we came to the conclusion that hot-fixes won't bring a big advantage, as they:

- Need to wait for the GCloud build verification
- Need to implement a mechanism to bring their changes back to develop branch. this is non-trivial because changes might cause conflicts which need to be fixed manually.

=> Conclusion is to prohibit pull requests directly to main from other branches than develop.

With that, the scope of this ticket is:

1. Add develop branch
2. Add CI build which checks if pull requests is targeting develop branch
3. Verify that GCloud build rebuilds for develop branch
