### ISSUE TITLE
Evaluate AWS Code Build for CI

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-release#390]
- Test batch builds https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build.html#batch_build_types
- Test nested batch builds with nested build_specs
- Test if each build of a batch build gets its own machine

**Comment by tomuben** [comment]
## Findings:

1. AWS CodeBuild has a nice integration with S3 and Logs. Hence we can remove the check_build.sh steps between the actual steps.
2. Must avoid using exaslct because the input/paths paths are not getting mounted by the AWS Build Docker images
3. There is the possibility to run builds locally. Added a simple setup-script and description how to do this in the branch. This does not work for batch-builds!
4. Builds can be triggered by AWS EventBridge, which could be an option for Nightly-Builds. However unfortunately this does not work for batch-builds.
5. Batch builds cannot be nested. There can be only one buildspec.yaml with the build-graph/build-matrix/build-list.

## Conclusion

AWS promises a simpler implementation of the CI builds, and increase in productivity due to the possiiblity to use batch-builds. However, the batch-builds still have some critical limitations.
