### ISSUE TITLE
exaslct does not throw an error when it fails to install an R package

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-release#772]
## Steps to reproduce

1. Use a flavor with R3.4.4 (standard 7.x flavor)
2. Add `Hmisc` R pkg to `flavor_customization/packages/r_cran_packages`
3. Run build command: `exaslct build --flavor-path ./flavors/standard-EXASOL-7.1.0` -> builds the image without errors
4. Login to the built docker image and execute R, then `library(Hmisc`) -> Observe

**Comment by tkilias** [comment]
The reason for this bug is that the package installation of R doesn't fail when packages can't be installed. It only shows it in the logs, which can be easily searched. There are potentially a few options to solve this issue. 

1. We could try to catch warnings thrown by R.
2. We could check if all packages were installed with _available.packages()_ after the _install.package()_ function returned
3. We check if we can load the package with _library(package)_
4. We could write integration tests for the packages.

The first solution doesn't guarantee to find all issues during installation, but would fail fast. The second one only guarantees that the package was installed, but not that it is loadable. The third one guarantees that a package is loadable, but not that it works.

I suggest implementing 1. and 2. as part of the installation script and 3. and 4. for important packages.

**Comment by tkilias** [comment]
Maybe option 3 can also be automated, but we probably should use the list of installed.packages() instead our list, in case packages get installed from a Github repository

**Comment by tkilias** [comment]
# Acceptance Criteria

- Check warnings after R package install
- Check if the list of installed packages contains the requested packages
- Check if we can load all installed packages
